### ISSUE TITLE
Allow controlling/setting general flag

### ISSUE THREAD

**Issue by SergioRius** [victronenergy/node-red-contrib-victron#100]
For advanced scheduling or based on more conditions than present on VS or assistants.

**Comment by mpvader** [comment]
that would be nice, but not something we're looking at soon since it involves firmware changes in the multis and quattros.

**Comment by SergioRius** [comment]
I thought that was the main reason for implementing node-red.

**Comment by mpvader** [comment]
Hi @SergioRius ; I'll close this issue; we won't be making this. I can see how it would be nice to do this, but its really too much of a stretch wrt how many people / different software has to be changed to make this work.
