### ISSUE TITLE
When grid drops, System grid (w) node sends null instead of zero.

### ISSUE THREAD

**Issue by SergioRius** [victronenergy/node-red-contrib-victron#106]
![image](https://user-images.githubusercontent.com/1693727/139597617-2126627d-68c6-4927-b9aa-ed65609c3861.png)

In this case provokes a crash in the following nodes.
Just curious if that's expected.
Could be easily (not straightforward) corrected in after process.

**Comment by dirkjanfaber** [comment]
Inserting a function node, containing:
```
if (! msg.payload) {
    msg.payload = 0;
}

return msg;
```
will replace the null value with a zero. 

But I am going to try to get some more background information on this.

**Comment by dirkjanfaber** [comment]
We want to differentiate between "device is not providing data" (`null` payload) and "device is measuring 0W" (`0` value). So this is planned behavior. You can expect the `null` value to remain possible in future updates.

**Comment by SergioRius** [comment]
> Inserting a function node, containing:

Yes, or a change node to follow with:
![image](https://user-images.githubusercontent.com/1693727/139702072-60a65d4e-81c6-4320-971d-b36088d27567.png)

> We want to differentiate between "device is not providing data" (null payload) and "device is measuring 0W"

OK. Just for clarification, I'm referring here to the inner AC measurements of a Multiplus2 when it "AC Ignores" the grid. No external meter involved.
