### ISSUE TITLE
Help text not wrapping

### ISSUE THREAD

**Issue by nmbath** [victronenergy/node-red-contrib-victron#110]
As per the screen shot. Help text is not wrapping properly. 

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/73959588/144135418-cae2da58-dcea-45e2-8e79-64252beac5b1.png">

**Comment by dirkjanfaber** [comment]
Now wrapping the long lines (by overruling the nowrap style back to normal). 
![image](https://user-images.githubusercontent.com/3098947/144196244-b80e6f26-7f23-4808-a247-adf16de56afb.png)
