### ISSUE TITLE
Show a disclaimer in Relay node, if the relay is not on manual operation

### ISSUE THREAD

**Issue by pkronstrom** [victronenergy/node-red-contrib-victron#12]
If the relay is set on, e.g. Generator Mode, show a disclaimer to the end user on node edit dialog.

The MVP solution for this would be to just show a warning text in relay node edit dialog:
"Please ensure that the relay is set to 'Manual' in settings (Relay -> Function)"

**Comment by pkronstrom** [comment]
_Can the relay still be toggled via dbus, even if it's set on generator use?_
In this case, one option would be to show both the warning message, and a greyed out relay option, for example.
-> Where can I see the current relay function?

**Comment by mpvader** [comment]
See gui code for how that function works. Its a setting.

Try toggling the relay when set to generator mode

**Comment by pkronstrom** [comment]
Implementation in https://github.com/victronenergy/node-red-contrib-victron/commit/8c4071038f96b82bfe8d6c02f9a8a0718649584e

The user is shown a warning message if the relay is reserved for some other function than manual.

<img width="493" alt="screenshot 2019-01-21 at 14 33 20" src="https://user-images.githubusercontent.com/11190027/51474928-8de79400-1d89-11e9-9398-c63c88bb8afa.png">

Trying to trigger the relay sends also a warning to the debug stream. The relay will not trigger in this case.

<img width="318" alt="screenshot 2019-01-21 at 14 33 36" src="https://user-images.githubusercontent.com/11190027/51474942-98a22900-1d89-11e9-9d42-07325d35f790.png">
