### ISSUE TITLE
Write csv file to flash drive. 

### ISSUE THREAD

**Issue by Benthegreat** [victronenergy/node-red-contrib-victron#138]
Hello All 

I am trying to use Node Red to write CSV information to the flash drive I have plugged in to the cerbo.  I have found the file path for the flash drive.  '/run/media/sda1' . When I SSH into the Cerbo I can see the files on the flash drive.  But I can't use Nodered to save data to that location.  
I get this error notice **"failed to write to file: Error: EACCES: permission denied, open '/run/media/sda1/csv data/EMMeter_202207.csv'"**

What do i need to do to allow node red access to that file to edit? 
![image](https://user-images.githubusercontent.com/25557411/179154829-705d4bca-8ebc-4843-9322-c38a1b841b99.png)
![image](https://user-images.githubusercontent.com/25557411/179154899-8796c6e4-e5ba-447c-aac4-8dd74cd66231.png)

Thanks for all the hard work.

**Comment by dirkjanfaber** [comment]
This has to do with the fact that Node-RED is running as user nodered. A `chown nodered:nodered /run/media/sda1/csv data/EMMeter_202207.csv` should do the trick.

Also see https://www.victronenergy.com/live/venus-os:large#node-red_faq.
