### ISSUE TITLE
Previously configured services; but now not available; should remain in the dropdown

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#14]
Consider this use case:

- User configures a system; with a battery on VE.Direct Port 1.
- Saves/deployes/stores/or-how-ever-thats-called-in-node-red-speak it
- Modifies if (plugs the BMV to VE.Direct port 2; which changes the device instance).
- Opens the node-red ui again
- He'll see a message below or on top of that node; saying that there is an issue with that battery(-service)
- He clicks it to see / re-configure

Now, the pulldown with the available battery services that he can choose from should not only show the available battery services; it should also show the one he had configured earlier; as the selected one.

**Comment by pkronstrom** [comment]
Fixed in https://github.com/victronenergy/node-red-contrib-victron/commit/331ad81db4757f6c3e5c244a48b162b9c2b844c4
