### ISSUE TITLE
Victron EV Charger

### ISSUE THREAD

**Issue by Smartrician** [victronenergy/node-red-contrib-victron#169]
Just on Node-Red and wanted to automate the EV Mode. Set to Auto from 04:30 to 00:30 then to Schedule from 00:30 to 04:30. The EV Mode only has Value Type 0 - Manual & 1 - Auto. 

Can you see if a Value “2 - Schedule” could be added to the node please.

Also to add a measurement to the node that can Lock and unlock the LCD screen so value types could be 
0 - Screen Unlocked & 1 -  Screen Locked 
Thank You 🙏

**Comment by dirkjanfaber** [comment]
Merged into the master branch. Closing this issue.
