### ISSUE TITLE
rename VE.Bus System reset to VE.Bus system restart

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#170]
I'm assuming thats just a textual update that doesn't have to break anything.

For background see here:
https://community.victronenergy.com/questions/34966/what-does-system-reset-on-multiplus.html?childToView=193256#answer-193256

and if you search on the todo (Victronese for beta-changelog 😉 ) then you'll find similar changes to the gui

**Comment by warwickchapman** [comment]
Excellent. The more plain language the better.

**Comment by dirkjanfaber** [comment]
Code is in merged. Closing this issue.
