### ISSUE TITLE
EV Charge Node, switch from 1Phase to 3Phase Charging Mode

### ISSUE THREAD

**Issue by Smartrician** [victronenergy/node-red-contrib-victron#176]
I have a few clients on 3 phase grid, but only uses 1 phase for the Victron equipment / power property.

I have added a Victron charge point, would like to charge car on 3 phase during night time cheap rate.

Then during the day, switch back to single phase but with Auto EVCP mode for excess sun.

I have setup the auto modes in node red nicely,  just stuck on switching the EVCP from single phase to 3 phase with a node.

Could this switch be added to the EVCP node please?

Thank You

**Comment by dirkjanfaber** [comment]
With the current EVCS this is not possible. The hardware cannot control the phases independently, which is needed to do what you want.
