### ISSUE TITLE
[BUG] Venus settings - DVCC Maximum charge voltage (V) missing in ESS Control

### ISSUE THREAD

**Issue by 1va13n7in** [victronenergy/node-red-contrib-victron#178]
Venus settings | DVCC Maximum charge voltage (V) is available in node ESS
Venus settings - DVCC Maximum charge voltage (V) is missing in node ESS Control

**Expected behavior**
Venus settings - DVCC Maximum charge voltage (V) should be available in node ESS Control

**Screenshots**
attached

**Hardware (please complete the following information):**
 - Hardware: [Cerbo GX]

**Software (please complete the following information):**

![2023-07-21-ESS-missing](https://github.com/victronenergy/node-red-contrib-victron/assets/100418771/f6c1eea4-b6b5-4964-9ca1-4538b0fbdd1a)
- node-red-contrib-victron version: 20230505191133
 
- Venus OS version: V3.00~39

**Comment by dirkjanfaber** [comment]
As DVCC voltage control won't work with all batteries (see https://www.victronenergy.com/media/pg/CCGX/en/dvcc---distributed-voltage-and-current-control.html), I am a bit hesitant to add it to the ESS control node.

**Comment by dirkjanfaber** [comment]
But the new input and output node support this. So feel free to use that (if your battery is supported).
