### ISSUE TITLE
[BUG] Enabling "httpNodeAuth" for dashboard breaks editing nodes

### ISSUE THREAD

**Issue by DarkZeros** [victronenergy/node-red-contrib-victron#182]
**Describe the bug**
If we want to expose the node red dashboard to the internet, it is a good idea to enable this feature and only allow password protected acceses.
But this breaks the victron nodes editing in the UI.
The nodes themselves work fine, it is just that is no longer possible to re-configure them.

**To Reproduce**
1. Enable "httpNodeAuth" in settings-user.js or settings.js
2. restart nodered or VenusOS
3. Open any victron node
4. Will ask for a password, no password seems to work, it just fails:

**Expected behavior**
Works normally

**Screenshots**
![image](https://github.com/victronenergy/node-red-contrib-victron/assets/6742754/a5baf4ad-eb29-43ba-a3fc-ced5d35947a0)
![image](https://github.com/victronenergy/node-red-contrib-victron/assets/6742754/70b27c08-8fe8-4022-9e73-48242d80eaeb)

**Hardware (please complete the following information):**
 - Hardware: VenusOS on Rpi3B

**Software (please complete the following information):**
 - node-red-contrib-victron version: 1.4.32
 - Venus OS version: v3.01 (but also failed on v2.xx that is why I updated)

**Comment by DarkZeros** [comment]
As I understand this problem is occuring because the Victron UI is requesting https://localhost:1881/victron/services/input-solarcharger and so on addresses to the server, and this requires authentication for httpNodeAuth. Looks like abug to me, since the feature is incompatible with a feature in node red.

**Comment by dirkjanfaber** [comment]
Alright, I see a possible overlooked feature here. I'll reopen the issue and check if user authentication can somehow be configured. Mind that the node-red-contrib-victron node don't use the http endpoints while running, it is only used on the edit panel (as other nodes also do).

**Comment by mpvader** [comment]
Careful here: exposing anything from a GX device, and especially things related to nodejs and thus Node-RED is a bad idea - from a security point of view.

I recommend strongly against it, even though I'm well aware that it might be quite some work to organise an alternate customisable solution to show a dashboard on the internet.

**Comment by dirkjanfaber** [comment]
Closing this issue as won't solve.
