### ISSUE TITLE
[ESS] Add peak shaving parameters to settings control node

### ISSUE THREAD

**Issue by inigoml** [victronenergy/node-red-contrib-victron#195]
**Is your feature request related to a problem? Please describe.**
Peak shaving options are not exposed at settings control node. There are countries like for example Spain where electric companies have different power periods, for example "high" and "low" power period. Usually low period is at night and is very cheap while high period is much more expensive. So, people select a higher power for "low period" and lower power for "high period". For example, you set a 10kW limit for "low period" in order to charge your electric car and a 5kW limit for "high period" for your regular home charges. Take into consideration that this is additional to low and high rates. It's just a power limitation.

**Describe the solution you'd like**
Exposing peak shaving settings will allow to program Victron inverter in order to enable two different power limits depending of the power period. In particular, be able to change maximum input and output power for Peak Shaving feature. 

**Additional context**
Included existing screenshot of ESS control node where no peak shaving settings are available.
Included existing screenshot of Victron Remote Control where peak shaving options can be set.
Attached simple node red flow in order to change peak shaving charge rate... when available.

<img width="363" alt="image" src="https://github.com/victronenergy/node-red-contrib-victron/assets/7486708/315462b8-3414-488d-afb7-b9547300dce1">

<img width="500" alt="image" src="https://github.com/victronenergy/node-red-contrib-victron/assets/7486708/11359490-c007-43a8-a07d-5d71153d5283">

<img width="635" alt="image" src="https://github.com/victronenergy/node-red-contrib-victron/assets/7486708/21d48258-51f1-4086-a995-8b230e59e24f">

**Comment by dirkjanfaber** [comment]
Good suggestion. Until I get around to adding it, you can already read from and write to this using the custom input and custom output node. 

You probably want to read from and write to these values:
<img width="513" alt="image" src="https://github.com/victronenergy/node-red-contrib-victron/assets/3098947/ab370d3c-c854-49ed-b2ae-52ed44d5fde2">

For the limits write `-1` to it to disable it. For changing the Peak Shaving setting either send a `1` (Always) or `0` (Above minimum SOC only).

Leaving this issue open so I don't forget adding it properly.

**Comment by inigoml** [comment]
Good suggestion! Will follow your advice in the interim.
Thank you!

**Comment by dirkjanfaber** [comment]
Closing as it is part of 1.5.20.
