### ISSUE TITLE
[BUG] Victron objects are not stored homogeneously as global objects

### ISSUE THREAD

**Issue by weichenb** [victronenergy/node-red-contrib-victron#198]
I appreciate that Victron objects that are requested in a flow, get also populated by global objects/variables. I observed that majority is stored in “victronenergy” object, but a few in a “com”/“victronenergy”-object.
![a765039614bff0d97c67bfa62075ad0326fdd462](https://github.com/user-attachments/assets/1cb3722e-4613-4951-a961-4c6b95e50753)

From my point of view it would makes sense to shift the “com”/"victronenergy-object into the “victronenergy”-object. In that case all objects would be well structured.

**Comment by dirkjanfaber** [comment]
All of the nodes _should_ store it there, so there must be something wrong on [this line](https://github.com/victronenergy/node-red-contrib-victron/blob/master/src/nodes/victron-nodes.js#L81), not converting the dbus path correctly. 

Do you happen to know which node is putting the data on the wrong place?

**Comment by weichenb** [comment]
It seems that all "settings"-parameters are impacted.
Since I use only a few in my flows, I cannot provide a comprehensive statement.
![Screenshot 2024-10-04 192657](https://github.com/user-attachments/assets/7a85f894-d1e1-453c-8163-82db3776cd35)

**Comment by dirkjanfaber** [comment]
Resolved in the latest release (which has been included in the latest beta release of Venus).

**Comment by weichenb** [comment]
> Resolved in the latest release (which has been included in the latest beta release of Venus).

Thanks Dirk,
can confirm that it is solved in latest beta.
