### ISSUE TITLE
[BUG] I cannot read/change the “AC import current limit (A)” of the Peak Shaving.

### ISSUE THREAD

**Issue by frbuceta** [victronenergy/node-red-contrib-victron#201]
**Describe the bug**
Cannot read or change the Peak Shaving import from the network from the NodeRed function

**To Reproduce**
1. Using node  'victron-{input/output}-settings'
2. I cannot select “AC import current limit (A)” which has been introduced in version 1.5.20.  e4f4fc4c9c1574c088407371b7559c16702723b6

**Expected behavior**
To be able to read and write this Peak Shaving parameter to be able to change it according to my network power which is different between hours.

**Screenshots**
![image](https://github.com/user-attachments/assets/2d5d04fe-e304-4dfd-9853-85271e0b8c1d)

**Flow**
If applicable, add a flow to help explain your problem.

**Hardware (please complete the following information):**
 - Hardware: Cerbo GX

**Software (please complete the following information):**
 - node-red-contrib-victron version: 1.5.23
 - Venus OS version: 3.51.0
 

**Additional context**

**Comment by dirkjanfaber** [comment]
You are right. Strangely enough the path isn't called 'AcImportLimit', but 'AcInputLimit' instead. 
Work-around is using the custom control node instead.

**Comment by dirkjanfaber** [comment]
Resolved in the upcoming version 1.6.0.
