### ISSUE TITLE
Automatically create node whitelists by using VRM dataAttribute csv exports

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#32]

**Comment by thlassche** [comment]
Here they are:

[dataattributes.zip](https://github.com/victronenergy/node-red-contrib-victron/files/2859543/dataattributes.zip)

**Comment by pkronstrom** [comment]
Node specification is now generated using VRM dataAttribute exports. Details on this process can be found on the readme [Generating the node specification file](https://github.com/victronenergy/node-red-contrib-victron#generating-the-node-specification-file)
