### ISSUE TITLE
Use VRM API to get d-bus path data instead of manual table exports

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#33]
Once #32 is completed; we can look into this; so its no longer necessary to now and then make an export from the VRM Database.

**Comment by mpvader** [comment]
```https://vrmapi.victronenergy.com/v2/admin/data-attributes```

The rest (dataAttributeEnums) is not available yet; and will be made available later.

**Comment by dirkjanfaber** [comment]
We might need to separate use-cases between dbus and modbus_tcp usage. Via modbus_tcp not all of the services are available.

By default (dbus connection) show all of the VRM attributes. When using modbus_tcp, only show the services that have the  'modbus_tcp' flag set.

We could use https://github.com/victronenergy/dbus_modbustcp/blob/master/CCGX-Modbus-TCP-register-list.xlsx as a source. But that beats a bit of the idea of only using the VRM API.

**Comment by dirkjanfaber** [comment]
Closing this as we are using the dbus_modbustcp list now, which works good enough.
