### ISSUE TITLE
External Node-red connecting to multiple GX devices

### ISSUE THREAD

**Issue by RobertSmart** [victronenergy/node-red-contrib-victron#46]
Hi,

I'm just having a play with this and would like to get information from more than one GX device on the same network. 

After a brief look there doesn't seem to be a way to do this as the DBUS address is hardcoded in the env_variables.

Is there a way to do this currently or are there any other work arounds?

Thanks,

R Smart

**Comment by sbender9** [comment]
@RobertSmart I'll look into this. Probably won't be simple, but should be doable.

**Comment by mpvader** [comment]
To add, whats the use case @RobertSmart ? What sort of victron products will be connected to each gx device?

If its for example tank levels, then an easier solution will be to hook the two GX-es up using VE.Can.

**Comment by mpvader** [comment]
closing, no explanation for why we should be doing this (welcome to re-open if there is a real good use case)
