### ISSUE TITLE
Node-red security needs documenting

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#68]
The way it works is that it takes the same password as Remote console.

Also Signalk security needs editing, it has its own settable admin password, unrelated to Remote Console.

**Comment by mpvader** [comment]
@sbender9 can you confirm that above is how its designed? Then I'll add it to the doc once I get round to it.

**Comment by dirkjanfaber** [comment]
I can confirm that this is how it is designed and how it has been added to the [documentation](https://www.victronenergy.com/live/venus-os:large#node-red_faq).
