### ISSUE TITLE
NodeRed Battery Monitor

### ISSUE THREAD

**Issue by shaneyake** [victronenergy/node-red-contrib-victron#73]
Hello,

Would it be possible to set battery monitor parameters in NodeRed, that way I can get BMS parameters via serial, USB, Modbus or MQTT and parse them via NodeRed on the Dbus.

Thanks,

Shane

**Comment by mpvader** [comment]
Hi shaneyake, it would require adding a new node to the pallete. More info in this issue: https://github.com/victronenergy/venus/issues/848.

I'll close this one, so we keep the list clean. all the best.
