### ISSUE TITLE
after restart nodes need to be reconfigured

### ISSUE THREAD

**Issue by dev-ale** [victronenergy/node-red-contrib-victron#74]
i am running venus on my raspi 3 as a large image wirh node red installed.
i have set up multiple venus nodes in node red.
when restart my raspi, all these nodes loos their config, i have to select the the new instance of the battery, or mppt again. does anybody has the same problem?

**Comment by dirkjanfaber** [comment]
This issue has been fixed in version 1.4.1. 

Until last week, the node-red palette did not see this updated version, but that has also been dealt with.
