### ISSUE TITLE
Node to read the "Active SoC Limit" (not the minimum SOC)

### ISSUE THREAD

**Issue by IoTPlay** [victronenergy/node-red-contrib-victron#75]
Hi, does a node exist to read the Active State of Charge limit?

![Screenshot 2021-04-30 at 10 35 39](https://user-images.githubusercontent.com/29833716/116670466-0c3b3380-a9a0-11eb-947b-fc4cc000e298.png)

**Comment by mpvader** [comment]
The solution for this is to add it to the ESS-output node. For which I think we already have an issue or todo item; assigning to dirkjan.

**Comment by dirkjanfaber** [comment]
Within the Venus gui, the _Active SOC limit_ is only shown if the Mode is set to _Optimized (with BatteryLife)_. 

The question is if we want to replicate the same logic here or just always have _Active SOC limit_ as a selectable input and let the user decide if it contains actual useful information.

**Comment by dirkjanfaber** [comment]
On the `faberd/bms-75` branch, I've added a selectable property for the path object, allowing to set the option to be selectable or not. This results in an unselectable grayed out option to be shown if the Mode is set to something else than _Optimized (with BatteryLife)_:  
![image](https://user-images.githubusercontent.com/3098947/130765605-a4b9c827-8d11-4ee4-bf31-382ade216805.png)

**Comment by mpvader** [comment]
Nice! So apparently node-red itself already supports this for properties? Or is all of that configuration window UI defined in our own code?

**Comment by dirkjanfaber** [comment]
It is all defined in our own code. (The _buildEditPanel_ function in `src/nodes/victron-nodes.html` to be precise)
