### ISSUE TITLE
AC Charger: /Mode path has wrong values

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/node-red-contrib-victron#80]
The components `input-accharger` and `output-accharger` have wrong values for the `/Mode` path (on/off control). See [here](https://github.com/victronenergy/node-red-contrib-victron/blob/master/src/services/services.json#L369) and [here](https://github.com/victronenergy/node-red-contrib-victron/blob/master/src/services/services.json#L1668). 
This should be the same as for `input-solarcharger` and `output-solarcharger`, see [here](https://github.com/victronenergy/node-red-contrib-victron/blob/master/src/services/services.json#L1698).

See also [this](https://github.com/victronenergy/vrm-portal/issues/226) issue.

**Comment by dirkjanfaber** [comment]
Fixed in (soon to be released) version 1.4.2. See pull [85](https://github.com/victronenergy/node-red-contrib-victron/pull/85) and [86](https://github.com/victronenergy/node-red-contrib-victron/pull/86).
