### ISSUE TITLE
Add node that allows making a new service on the D-Bus

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#82]
Right now, most nodes we have allow reading data. And a few nodes (ESS, and some more) can control systems.

But there is no node yet that actually puts a new service on the D-Bus. A use case would be reading data from some device via Node-RED, for example a wind meter, or temperature sensor, digital input, AC load, or similar, and wanting to have that available on the internal data structure on the GX, called dbus, so that it shows up on the gui, VRM, and so forth.

A few earlier issues asking for this are:
- https://github.com/victronenergy/node-red-contrib-victron/issues/73
- https://github.com/victronenergy/node-red-contrib-victron/issues/78

Note that on our (Victron) todo list, this issue is not a high priority one. Ofcourse as its all open source, anyone else wanting to do this is very welcome to; and please reach out for that either in this issue or here: https://community.victronenergy.com/spaces/31/mods.html

**Comment by dirkjanfaber** [comment]
Resolving this as (partially) solved in version 1.6.0. 

New virtual devices will get added in due time.

**Comment by kevstone122** [comment]
Hello together,

i have exactly the same problem / idea. How can i add some extra paths for some devices to be later visible in the cerbo gx screen. I have the existing virtual device, but i want to add some additional status value. I have to create some "custom path" to the dBus. How is this possible?

Thank you?
