### ISSUE TITLE
Add input `Dc/Battery/Temperature` under `com.victronenergy.system`

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/node-red-contrib-victron#95]
Requested via Slack (M. Corluka) to add the <strike>VE.Bus</strike> system temperature.

> The <strike>VE.Bus</strike> battery temperature dbus-obj-path is `Dc/Battery/Temperature`, under dbus-service-name `com.victronenergy.system`.

Note: item is not available under modbus_tcp.

**Comment by mpvader** [comment]
Hi DJ: note that this has nothing to do with VE.Bus; call me if you want me to explain

**Comment by dirkjanfaber** [comment]
I see, it only has to do with the dbus. I've edited the earlier comment and the title.
