### ISSUE TITLE
Temperature sensors: add support for Humidity and Battery Voltage

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/node-red-contrib-victron#97]
With support for the Ruuvi sensors coming up, the Humidy, Pressure and Battery Voltage should also be available.

**Comment by mpvader** [comment]
Careful, in the UI, that voltage is called Sensor battery, or Sensor battery voltage.

not just battery voltage.

**Comment by dirkjanfaber** [comment]
This change has been tested and merged with master.
